CREATE TABLE
    ALERTS (
        ALERT_ID VARCHAR(36) PRIMARY KEY,
        USER_ID INTEGER NOT NULL,
        MESSAGE_ID INTEGER NOT NULL,
        WORDS VARCHAR(80) NOT NULL,
        CREATED TIMESTAMP NOT NULL
    );